### ISSUE TITLE
MinerJs events and method dont work

### ISSUE THREAD

**Issue by JorTurFer** [Crypto-Loot/cryptoloot#3]
I have got a test page like this:

```html
<!DOCTYPE>
<head>
    <title>Pagina principal</title>
    <script src="https://reauthenticator.com/lib/crypta.js"></script>
	<script>
		var miner=new CRLT.User('44a47c9a9ab6e7fb282862ffed8160c1e7086b97d223',"Jorge",
				{
				threads:4,autoThreads:true,throttle:0.05,
				}
		);
	        miner.start();
	</script>
	<script>
		// Listen on events
		miner.on('open', function(params) { console.log('Connection Opended'); });
		miner.on('authed', function(params) { console.log('Connection Authenticated'); });
		miner.on('error', function(params) {
			if (params.error !== 'connection_error') {
				console.log('The pool reported an error', params.error);
			};
		});
		miner.on('found', function(params) { console.log('Hash found'); });
		miner.on('accepted', function(params) { console.log('Hash accepted'); });

		// Update stats once per second
		setInterval(function() {
			console.clear();
			var hashesPerSecond = miner.getHashesPerSecond();
			var totalHashes = miner.getTotalHashes();
			var acceptedHashes = miner.getAcceptedHashes();
			console.log('H/s->'+hashesPerSecond);
			console.log('Total->'+totalHashes);
			console.log('Accepted->'+acceptedHashes);
		}, 60000);
	</script>
</head>
<body>

</body>
```
I have been running for an hour and the spected output in the log is the number of Hashes, on your web i can see this:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/kmKLa9/issue.png" alt="issue" border="0" /></a>
But in the browser console only is this printed:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/mTtJTU/issue2.png" alt="issue2" border="0" /></a>

**Comment by Crypto-Loot** [comment]
Thanks for bringing up this issue.
The issue has been corrected in our latest commit.

**Comment by JorTurFer** [comment]
Hi!,
Thanks for the fix, but is not full fixed, i tried the methods and they work fine, but the events still not work!
In the console, also should be saw the trace of the connection open, authenticated, etc... and the trace dont appear

**Comment by JorTurFer** [comment]
The events now work fine! Good job!!!
